### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by bbrock25** [spartansystems/booster-kit-react#6]
How do we want to handle the tests in our app?

Should we try out mocha/enzyme or stick with jest?

Also, is there a need for the `tests/` directory anymore? It seems that the documentation suggests having the specs closer to the code. 

If its ok to remove that directory, and start investigating a good testing setup for react apps, I can get started on putting something together. I enjoyed using mocha for testing redux actions and reducers on the last app we worked on fwiw.

**Comment by samcdavid** [comment]
my vote is for jest

**Comment by bbrock25** [comment]
@samcdavid have you used jest?

**Comment by samcdavid** [comment]
very little, but I am opposed to the mocha ecosystem. I just want to include one thing that handles testing. Not 10 that no one fully knows how to use other than include everything and hope it works.

**Comment by bbrock25** [comment]
I would also like to consider Enzyme, as it seems to have a lot of momentum: https://github.com/airbnb/enzyme

**Comment by gabeweaver** [comment]
@bbrock25 @samcdavid current test suite looks like:

* BDD/TDD assertion library via [Chai](http://chaijs.com/)
* Unit Testing via [Enzyme](http://airbnb.io/enzyme/)
* Spies via [SinonJS](http://sinonjs.org/)
* Test runner via [Karma](https://karma-runner.github.io/1.0/index.html)
* Test framework via [Mocha](https://mochajs.org/)
* A bout 10 additional deps to support this...and it now appears there is lots of duplication amongst some of those in terms of purpose

Thing's ive been investigating:
* Test runner via [Ava](https://github.com/avajs/ava) because it's 2-3x faster than Mocha and has [good documentation](https://github.com/avajs/ava/blob/master/docs/recipes/react.md) of using Ava + Enzyme and a really good [workshop](https://github.com/kentcdodds/react-ava-workshop) that extensively covers setting up a test framework for react. 

[Why AVA](https://www.evernote.com/l/An37ElrKcSFJ2IqnMYgPbzRYn99_n3DWs3IB/image.png)

It also might be worthwhile to read through [this convo](https://github.com/facebookincubator/create-react-app/issues/80) folks in the `create-react-app` community were having about adding a standard, no config required, test framework to create react

**Comment by gabeweaver** [comment]
This [PR](https://github.com/spartansystems/booster-kit-react/pulls) completes the initial refactoring of the test suite. The readme has been updated to reflect the changes...but long and short, this is the solution we landed on:
* Test framework - Jasmine (under the hood of Jest)
* Feature tests - Jest + Nightmare
* Unit Tests - Test + Enzyme
